### ISSUE TITLE
Install Matplotlib as optional extra?

### ISSUE THREAD

**Issue by hugovk** [wpilibsuite/sphinxext-opengraph#100]
Thank you for the social card previews (https://github.com/wpilibsuite/sphinxext-opengraph/pull/88), they look really good!

(I would like to generate them for the CPython docs (https://docs.python.org/), but need to check some things first, e.g. how it works with translations, how to omit them from archives/non-web builds, check our deploy process works with ~500 images and 41 MB.)

We're already using this extension for OG metadata and it's working well.

Unfortunately, the new Matplotlib dependency broke our CI yesterday because we run doctests against the CPython 3.12 development branch, and unsurprisingly the NumPy dependency isn't yet compatible (for example: [numpy.txt](https://github.com/wpilibsuite/sphinxext-opengraph/files/10701242/numpy.txt), which begins with `RuntimeWarning: NumPy 1.24.2 may not yet support Python 3.12`).

So in the meantime we have to pin to the earlier 0.7.5 release (https://github.com/python/cpython/pull/101642).

Would it be possible to have Matplotlib installable as an optional extra? Even when using Python < 3.12, it's a pretty heavy dependency to install if you don't need it.

Docs:

* https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

Thanks again!

**Comment by Daltz333** [comment]
Yeah, this is something we want moving forward. I can't promise a timeline currently, but @TheTripleV was investigating this.

**Comment by tony** [comment]
@wpilibsuite Can you make socialcards / `matplotlib` optional? I'm getting bit by this. That's a super big dependency and likely going to break most users.

- My projects support **python 3.7** ([EOL](https://endoflife.date/python) support ends in 4 months and 2 weeks 27 Jun 2023)
- Due to this, numpy 1.21.1 is being forced when poetry locks `poetry.lock`

<details>

<summary>Error example</summary>

```
  ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects


  at ~/.config/asdf/installs/poetry/1.3.2/venv/lib/python3.11/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│
      1542│         return decode(output)
      1543│
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install ~/.cache/pypoetry/artifacts/f2/a4/4e/0208c493a2cf7704b33cc89eb971c275ad3cf9b8775a450427bd139f71/numpy-1.21.1.zip

  at ~/.config/asdf/installs/poetry/1.3.2/venv/lib/python3.11/site-packages/poetry/utils/pip.py:58 in pip_install
       54│
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│
```

</details>

**Comment by tony** [comment]
In poetry my workaround for now is this:

```toml
sphinxext-opengraph = "<0.8"  # https://github.com/wpilibsuite/sphinxext-opengraph/issues/100
```

Then `poetry update`

**Comment by Daltz333** [comment]
Note, I'm totally open to an external contributor PRing this.

**Comment by choldgraf** [comment]
Hey all - I'm happy with whatever y'all wanna do on the project, but I don't have time to do any of this work.

**Comment by TheTripleV** [comment]
I have a PR open to make matplotlib opt in. I'll get it merged and released.
