### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by tony** [wpilibsuite/sphinxext-opengraph#109]
Hi, thank you for the project!

- Can there be a release to include #104's packaging fix?
- Can #104 be included in a patch release before the drop of Python 3.7 in 651d0ac / #106

**Comment by Daltz333** [comment]
I want to see about #110 and then push a release

**Comment by MarshalX** [comment]
@tony I downgraded the package version so as not to be blocked by @Daltz333 

Maybe it will be useful for you too: https://github.com/MarshalX/atproto/pull/179
