### ISSUE TITLE
Newbie misunderstanding or perhaps more improvements for additional tags

### ISSUE THREAD

**Issue by coding-to-music** [wpilibsuite/sphinxext-opengraph#40]
I would like to add better SEO meta tags for sharing everywhere, this is an example site https://pandemic-overview.readthedocs.io/en/latest/

I am using this particular page as a sandbox https://pandemic-overview.readthedocs.io/en/latest/myGuides/Werkzeug-comprehensive-WSGI-web-application-library.html

I see this tester page shows what a page would look like when submitted to Facebook, Twitter, LinkendIn, Discord (would be good to see on the same page Google and Bing evaluation)
https://www.opengraph.xyz/url/https:%2F%2Fpandemic-overview.readthedocs.io%2Fen%2Flatest%2FmyGuides%2FWerkzeug-comprehensive-WSGI-web-application-library.html/

I see Bing has a link tester page https://www.bing.com/webmasters/urlinspection

I see google has a structured data testing tool
https://search.google.com/structured-data/testing-tool#

I would be interested in any improvements to tag generation, let me know if you would like me to test anything or help narrow down issues.

**Comment by Daltz333** [comment]
We've tried to abstain from providing platform specific SEO tags. You can add custom tags. There is an example in the README. I'm not sure I understand the issue here

**Comment by coding-to-music** [comment]
Ok Thanks
