### ISSUE TITLE
Use different image than the first one for subset of files

### ISSUE THREAD

**Issue by NicolasGensollen** [wpilibsuite/sphinxext-opengraph#45]
Hi there,

First of all, thanks for this great and useful tool! :+1: 
I was wondering if there is currently a way to NOT use the first image (even if there is one available) for a subset of files.

My use case is that my index page has a carousel of example images, such that the very first image gets picked but I would rather use the project logo instead for this page (which is set through `ogp_image`).
 
The config looks like this for now:
```
ogp_image = "https://.../logo.png"  # The logo image I want to use in some files although they have a first image availbale
ogp_use_first_image = True
```

If there is no way to do that now, would it be of interest as a new feature?

Hope this makes sense!

Nicolas

**Comment by Daltz333** [comment]
See #11. A refactor to make this possible is in-progress.
