### ISSUE TITLE
How do you feel about a theme enabling this extension for *all* its users?

### ISSUE THREAD

**Issue by pradyunsg** [wpilibsuite/sphinxext-opengraph#62]
The title says it all, honestly. In case you're curious about what theme this is for, it's https://github.com/pradyunsg/lutra/ (live at https://pradyunsg.me/lutra/). :)

For now, this theme isn't published on PyPI. The way that this works in the theme is that (1) the theme depends on this package and (2) if the theme is used, this extension is enabled as well (https://github.com/pradyunsg/lutra/blob/23ef5df197d3e0c85ea66453b1d9d6c361f59a77/src/lutra/__init__.py#L311).

**Comment by Daltz333** [comment]
Yeah, this should be fine. As with all dependencies, I do recommend pinning to a specific version, or at least a specific major version.
